#pragma once

#include "WindowsHider.h"

namespace bleak
{
	namespace window
	{
		enum class KeyCode : windows::WPARAM
		{
			LBUTTON = windows::VK_LBUTTON
			, RBUTTON = windows::VK_RBUTTON
			, CANCEL = windows::VK_CANCEL
			, MBUTTON = windows::VK_MBUTTON
			, XBUTTON1 = windows::VK_XBUTTON1
			, XBUTTON2 = windows::VK_XBUTTON2
			, BACK = windows::VK_BACK
			, TAB = windows::VK_TAB
			, CLEAR = windows::VK_CLEAR
			, RETURN = windows::VK_RETURN
			, SHIFT = windows::VK_SHIFT
			, CONTROL = windows::VK_CONTROL
			, MENU = windows::VK_MENU
			, PAUSE = windows::VK_PAUSE
			, CAPITAL = windows::VK_CAPITAL
			, KANA = windows::VK_KANA
			, HANGEUL = windows::VK_HANGEUL
			, HANGUL = windows::VK_HANGUL
			, JUNJA = windows::VK_JUNJA
			, FINAL = windows::VK_FINAL
			, HANJA = windows::VK_HANJA
			, KANJI = windows::VK_KANJI
			, ESCAPE = windows::VK_ESCAPE
			, CONVERT = windows::VK_CONVERT
			, NONCONVERT = windows::VK_NONCONVERT
			, ACCEPT = windows::VK_ACCEPT
			, MODECHANGE = windows::VK_MODECHANGE
			, SPACE = windows::VK_SPACE
			, PRIOR = windows::VK_PRIOR
			, NEXT = windows::VK_NEXT
			, END = windows::VK_END
			, HOME = windows::VK_HOME
			, LEFT = windows::VK_LEFT
			, UP = windows::VK_UP
			, RIGHT = windows::VK_RIGHT
			, DOWN = windows::VK_DOWN
			, SELECT = windows::VK_SELECT
			, PRINT = windows::VK_PRINT
			, EXECUTE = windows::VK_EXECUTE
			, SNAPSHOT = windows::VK_SNAPSHOT
			, INSERT = windows::VK_INSERT
			, DELETE = windows::VK_DELETE
			, HELP = windows::VK_HELP
			,Key0 = 0x30
			,Key1 = 0x31
			,Key2 = 0x32
			,Key3 = 0x33
			,Key4 = 0x34
			,Key5 = 0x35
			,Key6 = 0x36
			,Key7 = 0x37
			,Key8 = 0x38
			,Key9 = 0x39
			,KeyA = 0x41
			, KeyB = 0x42
			, KeyC = 0x43
			, KeyD = 0x44
			, KeyE = 0x45
			, KeyF = 0x46
			, KeyG = 0x47
			, KeyH = 0x48
			, KeyI = 0x49
			, KeyJ = 0x4A
			, KeyK = 0x4B
			, KeyL = 0x4C
			, KeyM = 0x4D
			, KeyN = 0x4E
			, KeyO = 0x4F
			, KeyP = 0x50
			, KeyQ = 0x51
			, KeyR = 0x52
			, KeyS = 0x53
			, KeyT = 0x54
			, KeyU = 0x55
			, KeyV = 0x56
			, KeyW = 0x57
			, KeyX = 0x58
			, KeyY = 0x59
			, KeyZ = 0x5A
			, LWIN = windows::VK_LWIN
			, RWIN = windows::VK_RWIN
			, APPS = windows::VK_APPS
			, SLEEP = windows::VK_SLEEP
			, NUMPAD0 = windows::VK_NUMPAD0
			, NUMPAD1 = windows::VK_NUMPAD1
			, NUMPAD2 = windows::VK_NUMPAD2
			, NUMPAD3 = windows::VK_NUMPAD3
			, NUMPAD4 = windows::VK_NUMPAD4
			, NUMPAD5 = windows::VK_NUMPAD5
			, NUMPAD6 = windows::VK_NUMPAD6
			, NUMPAD7 = windows::VK_NUMPAD7
			, NUMPAD8 = windows::VK_NUMPAD8
			, NUMPAD9 = windows::VK_NUMPAD9
			, MULTIPLY = windows::VK_MULTIPLY
			, ADD = windows::VK_ADD
			, SEPARATOR = windows::VK_SEPARATOR
			, SUBTRACT = windows::VK_SUBTRACT
			, DECIMAL = windows::VK_DECIMAL
			, DIVIDE = windows::VK_DIVIDE
			, F1 = windows::VK_F1
			, F2 = windows::VK_F2
			, F3 = windows::VK_F3
			, F4 = windows::VK_F4
			, F5 = windows::VK_F5
			, F6 = windows::VK_F6
			, F7 = windows::VK_F7
			, F8 = windows::VK_F8
			, F9 = windows::VK_F9
			, F10 = windows::VK_F10
			, F11 = windows::VK_F11
			, F12 = windows::VK_F12
			, F13 = windows::VK_F13
			, F14 = windows::VK_F14
			, F15 = windows::VK_F15
			, F16 = windows::VK_F16
			, F17 = windows::VK_F17
			, F18 = windows::VK_F18
			, F19 = windows::VK_F19
			, F20 = windows::VK_F20
			, F21 = windows::VK_F21
			, F22 = windows::VK_F22
			, F23 = windows::VK_F23
			, F24 = windows::VK_F24
			, NAVIGATION_VIEW = windows::VK_NAVIGATION_VIEW
			, NAVIGATION_MENU = windows::VK_NAVIGATION_MENU
			, NAVIGATION_UP = windows::VK_NAVIGATION_UP
			, NAVIGATION_DOWN = windows::VK_NAVIGATION_DOWN
			, NAVIGATION_LEFT = windows::VK_NAVIGATION_LEFT
			, NAVIGATION_RIGHT = windows::VK_NAVIGATION_RIGHT
			, NAVIGATION_ACCEPT = windows::VK_NAVIGATION_ACCEPT
			, NAVIGATION_CANCEL = windows::VK_NAVIGATION_CANCEL
			, NUMLOCK = windows::VK_NUMLOCK
			, SCROLL = windows::VK_SCROLL
			, OEM_NEC_EQUAL = windows::VK_OEM_NEC_EQUAL
			, OEM_FJ_JISHO = windows::VK_OEM_FJ_JISHO
			, OEM_FJ_MASSHOU = windows::VK_OEM_FJ_MASSHOU
			, OEM_FJ_TOUROKU = windows::VK_OEM_FJ_TOUROKU
			, OEM_FJ_LOYA = windows::VK_OEM_FJ_LOYA
			, OEM_FJ_ROYA = windows::VK_OEM_FJ_ROYA
			, LSHIFT = windows::VK_LSHIFT
			, RSHIFT = windows::VK_RSHIFT
			, LCONTROL = windows::VK_LCONTROL
			, RCONTROL = windows::VK_RCONTROL
			, LMENU = windows::VK_LMENU
			, RMENU = windows::VK_RMENU
			, BROWSER_BACK = windows::VK_BROWSER_BACK
			, BROWSER_FORWARD = windows::VK_BROWSER_FORWARD
			, BROWSER_REFRESH = windows::VK_BROWSER_REFRESH
			, BROWSER_STOP = windows::VK_BROWSER_STOP
			, BROWSER_SEARCH = windows::VK_BROWSER_SEARCH
			, BROWSER_FAVORITES = windows::VK_BROWSER_FAVORITES
			, BROWSER_HOME = windows::VK_BROWSER_HOME
			, VOLUME_MUTE = windows::VK_VOLUME_MUTE
			, VOLUME_DOWN = windows::VK_VOLUME_DOWN
			, VOLUME_UP = windows::VK_VOLUME_UP
			, MEDIA_NEXT_TRACK = windows::VK_MEDIA_NEXT_TRACK
			, MEDIA_PREV_TRACK = windows::VK_MEDIA_PREV_TRACK
			, MEDIA_STOP = windows::VK_MEDIA_STOP
			, MEDIA_PLAY_PAUSE = windows::VK_MEDIA_PLAY_PAUSE
			, LAUNCH_MAIL = windows::VK_LAUNCH_MAIL
			, LAUNCH_MEDIA_SELECT = windows::VK_LAUNCH_MEDIA_SELECT
			, LAUNCH_APP1 = windows::VK_LAUNCH_APP1
			, LAUNCH_APP2 = windows::VK_LAUNCH_APP2
			, OEM_1 = windows::VK_OEM_1
			, OEM_PLUS = windows::VK_OEM_PLUS
			, OEM_COMMA = windows::VK_OEM_COMMA
			, OEM_MINUS = windows::VK_OEM_MINUS
			, OEM_PERIOD = windows::VK_OEM_PERIOD
			, OEM_2 = windows::VK_OEM_2
			, OEM_3 = windows::VK_OEM_3
			, GAMEPAD_A = windows::VK_GAMEPAD_A
			, GAMEPAD_B = windows::VK_GAMEPAD_B
			, GAMEPAD_X = windows::VK_GAMEPAD_X
			, GAMEPAD_Y = windows::VK_GAMEPAD_Y
			, GAMEPAD_RIGHT_SHOULDER = windows::VK_GAMEPAD_RIGHT_SHOULDER
			, GAMEPAD_LEFT_SHOULDER = windows::VK_GAMEPAD_LEFT_SHOULDER
			, GAMEPAD_LEFT_TRIGGER = windows::VK_GAMEPAD_LEFT_TRIGGER
			, GAMEPAD_RIGHT_TRIGGER = windows::VK_GAMEPAD_RIGHT_TRIGGER
			, GAMEPAD_DPAD_UP = windows::VK_GAMEPAD_DPAD_UP
			, GAMEPAD_DPAD_DOWN = windows::VK_GAMEPAD_DPAD_DOWN
			, GAMEPAD_DPAD_LEFT = windows::VK_GAMEPAD_DPAD_LEFT
			, GAMEPAD_DPAD_RIGHT = windows::VK_GAMEPAD_DPAD_RIGHT
			, GAMEPAD_MENU = windows::VK_GAMEPAD_MENU
			, GAMEPAD_VIEW = windows::VK_GAMEPAD_VIEW
			, GAMEPAD_LEFT_THUMBSTICK_BUTTON = windows::VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON
			, GAMEPAD_RIGHT_THUMBSTICK_BUTTON = windows::VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON
			, GAMEPAD_LEFT_THUMBSTICK_UP = windows::VK_GAMEPAD_LEFT_THUMBSTICK_UP
			, GAMEPAD_LEFT_THUMBSTICK_DOWN = windows::VK_GAMEPAD_LEFT_THUMBSTICK_DOWN
			, GAMEPAD_LEFT_THUMBSTICK_RIGHT = windows::VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT
			, GAMEPAD_LEFT_THUMBSTICK_LEFT = windows::VK_GAMEPAD_LEFT_THUMBSTICK_LEFT
			, GAMEPAD_RIGHT_THUMBSTICK_UP = windows::VK_GAMEPAD_RIGHT_THUMBSTICK_UP
			, GAMEPAD_RIGHT_THUMBSTICK_DOWN = windows::VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN
			, GAMEPAD_RIGHT_THUMBSTICK_RIGHT = windows::VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT
			, GAMEPAD_RIGHT_THUMBSTICK_LEFT = windows::VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT
			, OEM_4 = windows::VK_OEM_4
			, OEM_5 = windows::VK_OEM_5
			, OEM_6 = windows::VK_OEM_6
			, OEM_7 = windows::VK_OEM_7
			, OEM_8 = windows::VK_OEM_8
			, OEM_AX = windows::VK_OEM_AX
			, OEM_102 = windows::VK_OEM_102
			, ICO_HELP = windows::VK_ICO_HELP
			, ICO_00 = windows::VK_ICO_00
			, PROCESSKEY = windows::VK_PROCESSKEY
			, ICO_CLEAR = windows::VK_ICO_CLEAR
			, PACKET = windows::VK_PACKET
			, OEM_RESET = windows::VK_OEM_RESET
			, OEM_JUMP = windows::VK_OEM_JUMP
			, OEM_PA1 = windows::VK_OEM_PA1
			, OEM_PA2 = windows::VK_OEM_PA2
			, OEM_PA3 = windows::VK_OEM_PA3
			, OEM_WSCTRL = windows::VK_OEM_WSCTRL
			, OEM_CUSEL = windows::VK_OEM_CUSEL
			, OEM_ATTN = windows::VK_OEM_ATTN
			, OEM_FINISH = windows::VK_OEM_FINISH
			, OEM_COPY = windows::VK_OEM_COPY
			, OEM_AUTO = windows::VK_OEM_AUTO
			, OEM_ENLW = windows::VK_OEM_ENLW
			, OEM_BACKTAB = windows::VK_OEM_BACKTAB
			, ATTN = windows::VK_ATTN
			, CRSEL = windows::VK_CRSEL
			, EXSEL = windows::VK_EXSEL
			, EREOF = windows::VK_EREOF
			, PLAY = windows::VK_PLAY
			, ZOOM = windows::VK_ZOOM
			, NONAME = windows::VK_NONAME
			, PA1 = windows::VK_PA1
			, OEM_CLEAR = windows::VK_OEM_CLEAR
		};
		constexpr windows::WPARAM operator+(KeyCode e)
		{
			return static_cast<windows::WPARAM>(e);
		}
	}
}